### ISSUE TITLE
joineR in CR with multiple covariates

### ISSUE THREAD

**Issue by abadereddeen** [petephilipson/joineR#15]
I tried the updated version, now the survival model doesn't read the first covariate in a list of multiple covariates to adjust for, the error is:
Error : in match.arg(model): object x1 not found.
I might be missing something

**Comment by graemeleehickey** [comment]
Did you fix this? I cannot reproduce this problem. 

After the last issue, I have (re-)taken over the package from Pete, so please file any issues under graemeleehickey/joineR.

**Comment by abadereddeen** [comment]
I am working on it.
Will file any future issues under graemeleehickey/joineR

Thank you so much!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
