### ISSUE TITLE
Issues of running competing risks data

### ISSUE THREAD

**Issue by shanpengli** [petephilipson/joineR#5]
Hi, I encountered some issues when I was running your toy example data:

data(epileptic)
epileptic$interaction <- with(epileptic, time * (treat == "LTG"))
longitudinal <- epileptic[, c(1:3, 13)]
survival <- UniqueVariables(epileptic, c(4, 6), "id")
baseline <- UniqueVariables(epileptic, c("treat", "age"), "id")
data <- jointdata(longitudinal = longitudinal,
survival = survival,
baseline = baseline,
id.col = "id",
time.col = "time")
fit2 <- joint(data = data,
long.formula = dose ~ time + treat + interaction + age,
surv.formula = Surv(with.time, with.status2) ~ treat + age,
longsep = FALSE, survsep = FALSE,
gpt = 3)
summary(fit2)

> Error in eval(predvars, data, env) : object 'age' not found
> 
I want to build a survival sub-model with multiple covariates but I failed to do so. Do you know how to fix this issue?

**Comment by abadereddeen** [comment]
I am having the same issue with competing risk

**Comment by abadereddeen** [comment]
have you figured out the issue with joineR in competing risk?

**Comment by graemeleehickey** [comment]
Fixed (see https://github.com/graemeleehickey/joineR). Package is going to be submitted to CRAN today.

**Comment by abadereddeen** [comment]
Thank you so much!

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by abadereddeen** [comment]
I tried the updated version of joineR. Unfortunately, it is not working.
Now the first covariate listed is not being read, it gives the error:
Error : In match.arg(model) object var1 not found?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
